Introduce decisions-embedded-mode-example
bamoe/bamoe-docs-source-code-examples pull request #5
Opened 2024-06-05 13:06 UTC by jomarko

2024-06-05 13:53 UTC, gitgabrio requested changes
HI @jomarko 
Thanks for PR, but I have the impression we are mixing two different things here `decisions`(DMN) and `rules` (DRL)
The current documentation does not clearly separate them because, until now, we dealt only with DMN, but they should be clearly separated, IMO (even in the code example).

@baldimir @porcelli

2024-06-05 13:53 UTC, gitgabrio commented on decisions-embedded-mode-example/src/main/java/com/ibm/bamoe/decisions/embedded/DecisionsEmbeddedModeExample.java
> +        System.out.println(executionResults.getResults().get("application"));
Hi @jomarko 
Pls replace System.out.println with logger usage

2024-06-05 13:53 UTC, gitgabrio commented on decisions-embedded-mode-example/src/main/java/com/ibm/bamoe/decisions/embedded/DecisionsEmbeddedModeExample.java
> +        System.out.println("-----> Now we execute rules in the stateless session <-----");
I'm confused, but IINW there is no relationship with DRL execution and DMN one, and I can't see any embedding: could you please clarify that ?

2024-06-10 11:37 UTC, gitgabrio requested changes
Thanks for the PR. There is just one thing to fix, i.e. pls replace all System.out with proper logging. Beside that, everything seems fine

2024-06-10 11:37 UTC, gitgabrio commented on rules-embedded-mode-example/src/main/java/com/ibm/bamoe/rules/embedded/RulesEmbeddedModeExample.java
> +        System.out.println("-----> Now we execute rules in the stateless session <-----");
Hi @jomarko 
Could you please replace System.out with proper logging ?  Thanks!

2024-06-10 12:01 UTC, jomarko commented
@gitgabrio comments addressed .

2024-06-10 12:17 UTC, gitgabrio approved these changes

2024-06-10 12:51 UTC, merged